# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RGBToReflectance
                                 A QGIS plugin
 Converts RGB values to reflectance
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-11
        copyright            : (C) 2025 by Kaden Patten, Alexander Hernandez, USDA ARS FRR
        email                : kaden.patten@usda.gov
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


import os, platform, subprocess, sys
from contextlib import redirect_stderr

def plugin_prep():
    temp = os.getcwd()
    
    if platform.system() == "Windows":
        import pip
        installer = "install.bat"
        bin_parent = sys.executable.split("bin")[0]
        py_version = [p for p in os.listdir(os.path.join(bin_parent,"apps")) if "Python3" in p][0]
        qgis_py_path = os.path.join(bin_parent,"apps",py_version,"python.exe")
        installer = os.path.join(os.path.dirname(__file__), installer)
        os.chdir(os.path.dirname(__file__))
        
        with open('install_err.log','w') as f:
            out = str(subprocess.run([installer,qgis_py_path], capture_output=True))
            f.write(str(out))
            if sys.stdout is None:
                sys.stdout = f
            with redirect_stderr(f):
                pip.main(["install","-t",os.path.join(os.getcwd(),"rrenv\\Lib\\site-packages"),"-r",os.path.join(os.getcwd(),"requirements.txt")])
    if platform.system() == "Linux" or platform.system() == "Darwin":
        installer = "install.sh"
        installer = os.path.join(os.path.dirname(__file__), installer)
        os.chdir(os.path.dirname(__file__))
        res = subprocess.run(["bash",installer], capture_output=True)
        print(res)
        with open('install_err.log','w') as f:
            f.write(str(res))
    
    os.chdir(temp)

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RGBToReflectance class from file RGBToReflectance.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """

    if not os.path.exists(os.path.join(os.path.dirname(__file__),"rrenv")):
        plugin_prep()
    #
    from .rgb_to_reflectance import RGBToReflectance
    return RGBToReflectance(iface)
